export const GENERAL = {
  MESSAGE_SUCCEFULL: 'Proceso exitoso',
  STATUS_CREATED: 'Creado',
  EXCEPTION_CODE: {
    GENERATE_TOKEN: '[ER-GTHS]',
    GENERATE_HASH_KEY: '[ER-GHAK]',
    REGISTER_SECURITY: '[ER-RSFU]',
    REGISTER_HASH_KEY: '[ER-RGHS]',
    FIND_SECURITY_TOKEN: '[ER-FSBT]',
    DELETE_SECURITY_TOKEN: '[ER-DSTE]',
    REGISTER_ACCOUNT: '[ER-RGAC]',
  },
};
